Camera:
  color_order: RGB
  cols: 640
  cx: 303.27640639380814
  cy: 235.76456910093665
  fps: 30.0
  fx: 256.06277082424594
  fy: 246.94753111056662
  k1: -0.01702685537239949
  k2: 0.011748839004928848
  k3: -0.003218339690431988
  model: perspective
  name: Nargess' Webcam
  p1: 0.0009388618699439178
  p2: -0.029168273968797863
  rows: 480
  setup: monocular
Feature:
  ini_fast_threshold: 20
  min_fast_threshold: 7
  name: default ORB feature extraction setting
  num_levels: 8
  scale_factor: 1.2
Mapping:
  baseline_dist_thr_ratio: 0.02
  num_covisibilities_for_landmark_fusion: 20
  num_covisibilities_for_landmark_generation: 20
  redundant_obs_ratio_thr: 0.9
PangolinViewer:
  camera_line_width: 3
  camera_size: 0.08
  graph_line_width: 1
  keyframe_line_width: 1
  keyframe_size: 0.05
  point_size: 2
  viewpoint_f: 400
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
Preprocessing:
  min_size: 800
