Camera:
  color_order: RGB
  cols: 640
  cx: 320.2204033062567
  cy: 231.2339953851215
  fps: 30.0
  fx: 249.55028318243194
  fy: 251.35081038684598
  k1: -0.00022924421513655338
  k2: -0.0024827153936356865
  k3: -0.003601306984077972
  model: perspective
  name: Nargess' Webcam
  p1: -0.00048077133885851716
  p2: -0.0004811060204570792
  rows: 480
  setup: monocular
Feature:
  ini_fast_threshold: 20
  min_fast_threshold: 7
  name: default ORB feature extraction setting
  num_levels: 8
  scale_factor: 1.2
Mapping:
  baseline_dist_thr_ratio: 0.02
  num_covisibilities_for_landmark_fusion: 20
  num_covisibilities_for_landmark_generation: 20
  redundant_obs_ratio_thr: 0.9
PangolinViewer:
  camera_line_width: 3
  camera_size: 0.08
  graph_line_width: 1
  keyframe_line_width: 1
  keyframe_size: 0.05
  point_size: 2
  viewpoint_f: 400
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
Preprocessing:
  min_size: 800
