Camera:
  color_order: RGB
  cols: 640
  cx: 328.7437334131659
  cy: 234.27482836496304
  fps: 30.0
  fx: 258.01591950878856
  fy: 254.61961838592865
  k1: -0.02370425904000283
  k2: 0.06091139728586446
  k3: -0.05823402904784376
  model: perspective
  name: Nargess' Webcam
  p1: 0.004568380943198548
  p2: -0.004407276986236035
  rows: 480
  setup: monocular
Feature:
  ini_fast_threshold: 20
  min_fast_threshold: 7
  name: default ORB feature extraction setting
  num_levels: 8
  scale_factor: 1.2
Mapping:
  baseline_dist_thr_ratio: 0.02
  num_covisibilities_for_landmark_fusion: 20
  num_covisibilities_for_landmark_generation: 20
  redundant_obs_ratio_thr: 0.9
PangolinViewer:
  camera_line_width: 3
  camera_size: 0.08
  graph_line_width: 1
  keyframe_line_width: 1
  keyframe_size: 0.05
  point_size: 2
  viewpoint_f: 400
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
Preprocessing:
  min_size: 800
