Camera:
  color_order: RGB
  cols: 640
  cx: 318.73695296999887
  cy: 237.051938856692
  fps: 30.0
  fx: 256.56288169866957
  fy: 254.17796803366738
  k1: -0.07086394615999969
  k2: 0.08850794592776348
  k3: -0.04577052014427504
  model: perspective
  name: Nargess' Webcam
  p1: -0.007287542866891743
  p2: 0.010804660470299786
  rows: 480
  setup: monocular
Feature:
  ini_fast_threshold: 20
  min_fast_threshold: 7
  name: default ORB feature extraction setting
  num_levels: 8
  scale_factor: 1.2
Mapping:
  baseline_dist_thr_ratio: 0.02
  num_covisibilities_for_landmark_fusion: 20
  num_covisibilities_for_landmark_generation: 20
  redundant_obs_ratio_thr: 0.9
PangolinViewer:
  camera_line_width: 3
  camera_size: 0.08
  graph_line_width: 1
  keyframe_line_width: 1
  keyframe_size: 0.05
  point_size: 2
  viewpoint_f: 400
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
Preprocessing:
  min_size: 800
