Camera:
  color_order: RGB
  cols: 640
  cx: 313.019344172618
  cy: 233.76984388492957
  fps: 30.0
  fx: 254.92819318193392
  fy: 257.8380200385567
  k1: 0.010982391400246809
  k2: 0.0012346214216205822
  k3: -0.017279387191724994
  model: perspective
  name: Nargess' Webcam
  p1: -0.003524839284748835
  p2: -0.005498091263692889
  rows: 480
  setup: monocular
Feature:
  ini_fast_threshold: 20
  min_fast_threshold: 7
  name: default ORB feature extraction setting
  num_levels: 8
  scale_factor: 1.2
Mapping:
  baseline_dist_thr_ratio: 0.02
  num_covisibilities_for_landmark_fusion: 20
  num_covisibilities_for_landmark_generation: 20
  redundant_obs_ratio_thr: 0.9
PangolinViewer:
  camera_line_width: 3
  camera_size: 0.08
  graph_line_width: 1
  keyframe_line_width: 1
  keyframe_size: 0.05
  point_size: 2
  viewpoint_f: 400
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
Preprocessing:
  min_size: 800
