Camera:
  color_order: RGB
  cols: 640
  cx: 361.1026078627837
  cy: 206.08181015067285
  fps: 30.0
  fx: 350.91624911492465
  fy: 361.6556021566725
  k1: 0.18946209966709573
  k2: 2.7344644029326384
  k3: -4.3728042377363865
  model: perspective
  name: Nargess' Webcam
  p1: -0.025790798309327036
  p2: 0.09198388221628914
  rows: 480
  setup: monocular
Feature:
  ini_fast_threshold: 20
  min_fast_threshold: 7
  name: default ORB feature extraction setting
  num_levels: 8
  scale_factor: 1.2
Mapping:
  baseline_dist_thr_ratio: 0.02
  num_covisibilities_for_landmark_fusion: 20
  num_covisibilities_for_landmark_generation: 20
  redundant_obs_ratio_thr: 0.9
PangolinViewer:
  camera_line_width: 3
  camera_size: 0.08
  graph_line_width: 1
  keyframe_line_width: 1
  keyframe_size: 0.05
  point_size: 2
  viewpoint_f: 400
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
Preprocessing:
  min_size: 800
