# TUM RGBD monocular model for your webcam

#==============#
# Camera Model #
#==============#

Camera:
  name: "Your Webcam"
  setup: "monocular"
  model: "perspective"

  # Intrinsic parameters
  fx: 527.95518594
  fy: 480.85304377
  cx: 501.61726806
  cy: 300.71630233

  # Distortion coefficients
  k1: 0.18221283
  k2: -0.16164479
  p1: 0.01295441
  p2: 0.08238938
  k3: 0.08638778

  fps: 30.0
  cols: 640
  rows: 480

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  min_size: 800

#================#
# ORB Parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.05
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.08
  camera_line_width: 3
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
  viewpoint_f: 400

